{{- if and (not .Values.provider.existingSecret) .Values.provider.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flint-controller.providerSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flint-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "flint-controller.providerKeyEnv" . }}: {{ .Values.provider.apiKey | quote }}
{{- end }}
