apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portier-broker.fullname" . }}-lang
  labels:
    {{- include "portier-broker.labels" $ | nindent 4 }}
data:
  {{- (.Files.Glob "files/lang/**.po").AsConfig | nindent 2 }}
binaryData:
  {{- (.Files.Glob "files/lang/**.mo").AsSecrets | nindent 2 }}
