{{- with .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "portier-broker.fullname" $ }}-postmark-token"
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  token: {{ required "must set postmark token" .entries.postmarkToken | b64enc }}
{{- end }}
{{- end }}
