apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "portier-broker.labels" . | nindent 4 }}
  name: {{ include "portier-broker.fullname" . }}
spec:
  ports:
  - name: broker
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
  selector:
    {{- include "portier-broker.selectorLabels" . | nindent 8 }}
  type: ClusterIP
