apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portier-broker.fullname" . }}-static
  labels:
    {{- include "portier-broker.labels" $ | nindent 4 }}
data:
  {{- (.Files.Glob "files/static/**").AsConfig | nindent 2 }}
