apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetailor-server.serviceAccountName" . }}
  labels:
    {{- include "kubetailor-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "Must set service account to be used on kubetailor managed deployments" .Values.config.kubetailor.deployment.serviceAccount }}
  namespace: {{ required "Must set namespace to be used for kubetailor managed deployments" .Values.config.kubetailor.namespace }}
